services:
  web:
    container_name: web
    build: .
    command: [ "./main" ]
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgresql_data: